var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                             o  ",
   "                                                                                ",
   "                                                          o      xxxxxxxxxxxxxxx",
   "                                                                 x              ",
   "                                                    o     x      x              ",
   "                                                                 x              ",
   "                                              o                  x              ",
   "                                                                 x              ",
   "                                                                 x              ",
   "                                                                 x              ",
   "                                                                 x              ",
   "                 o         o        +                            x              ",
   "     @                                                           x              ",
   "xxxxxxxxxxxx   xxxxxx    xxxxxx   xxxxx           xxxxx    xxxxxxx              ",
   "           x   x    x    x    x   x   x           x   x    x                    ",
   "           x!!!x    x!!!!x    x!!!x   x!!!!!!!!!!!x   x!!!!x                    ",
   "           x!!!x    x!!!!x    x!!!x   x!!!!!!!!!!!x   x!!!!x                    ",
   "           xxxxx    xxxxxx    xxxxx   xxxxxxxxxxxxx   xxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
[  "             xxxxxx                                                                                               ",
   "             x!!!!x                                                                         xxxxxxxx              ",
   "             xx!!xx                                                                         x!!!!!!x              ",
   "               |                                                                               |                  ",
   "                                                                                                                  ",
   "                        o                                                                                         ",
   "                        xx                                                                                   o    ",
   "  @                                                 +                  xxx       x                                ",
   "xxxxxx   x   o   x                 o        xx    xxxxxx                         x  o                xx    xxxxxxx",
   "     x       x                      x             x    x                         x  o              xx      x      ",
   "     x                                            x    x                         x  o            xx        x      ",
   "     x                                            x    x                         xxxxxxxxxxxxxxx           x      ",
   "     x                                            x    x                                                   x      ",
   "     x                                            x    x                                                   x      ",
   "     x                                            x    x                                                   x      ",
   "     x                                            x    x                                                   x      ",
   "     x                                            x    x                                                   x      ",
   "     x                                            x    x                                                   x      ",
   "     x                                            x    x                                                   x      ",
   "     xxx                                          x    x                                                   x      ",
   "       x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxx    x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x      ",
   "       x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x          x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x      ",
   "       x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x          x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x      ",
   "       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      ",
   "                                                                                                                  "]
 ];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
